export const REQUIRED_META = ["description", "viewport"];
export const REQUIRED_LINK_REL = ["canonical"];
export const OPEN_GRAPH_TAGS = ["og:title", "og:description", "og:image", "og:url"];
export const TWITTER_TAGS = ["twitter:card", "twitter:title", "twitter:image"];
export const LEGACY_DOM_TAGS = ["center", "font", "marquee"];
export const HTTP_PROTOCOLS = new Set(["http:", "https:"]);
export const THIN_CONTENT_WORD_THRESHOLD = 300;
export const REDIRECT_STATUS_CODES = new Set([301, 302]);
export const KNOWN_BOT_BLOCKERS = new Set([
  "facebook.com",
  "www.facebook.com",
  "linkedin.com",
  "www.linkedin.com",
  "twitter.com",
  "x.com",
  "instagram.com",
  "www.instagram.com",
  "reddit.com",
  "www.reddit.com",
]);
export const BROKEN_STATUS_CODE_MIN = 400;
export const BROKEN_STATUS_CODE_MAX = 599;
export const HEAD_FALLBACK_STATUS_CODE = 405;
export const LINK_CHECK_CONCURRENCY = 5;
export const LINK_CHECK_TIMEOUT_MS = 5000;
export const LINK_CHECK_GET_FALLBACK_TIMEOUT_MS = 2500;
export const LINK_CHECK_USER_AGENT =
  "Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/122.0.0.0 Safari/537.36 ThinkShipSEOAuditor/1.0";
export const STOP_WORDS = new Set([
  "a",
  "about",
  "above",
  "after",
  "again",
  "against",
  "all",
  "am",
  "an",
  "and",
  "any",
  "are",
  "as",
  "at",
  "be",
  "because",
  "been",
  "before",
  "being",
  "below",
  "between",
  "both",
  "but",
  "by",
  "can",
  "could",
  "did",
  "do",
  "does",
  "doing",
  "down",
  "during",
  "each",
  "few",
  "for",
  "from",
  "further",
  "had",
  "has",
  "have",
  "having",
  "he",
  "her",
  "here",
  "hers",
  "herself",
  "him",
  "himself",
  "his",
  "how",
  "i",
  "if",
  "in",
  "into",
  "is",
  "it",
  "its",
  "itself",
  "just",
  "me",
  "more",
  "most",
  "my",
  "myself",
  "no",
  "nor",
  "not",
  "now",
  "of",
  "off",
  "on",
  "once",
  "only",
  "or",
  "other",
  "our",
  "ours",
  "ourselves",
  "out",
  "over",
  "own",
  "same",
  "she",
  "should",
  "so",
  "some",
  "such",
  "than",
  "that",
  "the",
  "their",
  "theirs",
  "them",
  "themselves",
  "then",
  "there",
  "these",
  "they",
  "this",
  "those",
  "through",
  "to",
  "too",
  "under",
  "until",
  "up",
  "very",
  "was",
  "we",
  "were",
  "what",
  "when",
  "where",
  "which",
  "while",
  "who",
  "whom",
  "why",
  "will",
  "with",
  "you",
  "your",
  "yours",
  "yourself",
  "yourselves",
]);
export const SCORE_WEIGHTS = {
  MISSING_META: 8,
  MISSING_CANONICAL: 8,
  MISSING_H1: 10,
  MULTIPLE_H1: 3,
  INVALID_JSON_LD: 15,
  THIN_CONTENT: 10,
  MISSING_ALT: 2,
  LEGACY_TAG: 4,
  INTERNAL_BROKEN_LINK: 5,
  INTERNAL_BROKEN_LINK_MAX: 25,
  EXTERNAL_BROKEN_LINK: 2,
  EXTERNAL_BROKEN_LINK_MAX: 10,
  MISSING_OG_IMAGE: 5,
  BLOCKING_ROOT_ROBOTS: 20,
  MISSING_SITEMAP: 5,
};
export const PRIORITY = {
  HIGH: "HIGH",
  MEDIUM: "MEDIUM",
  LOW: "LOW",
};
